name: service-connections/jdbc

on:
  push:
    paths:
      - "service-connections/jdbc/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "maven"
      - name: Build with Maven
        run: mvn -B package --file service-connections/jdbc/pom.xml
